spring:
  datasource:
    url: jdbc:mysql://localhost/beerens
    username: beerens
    password: beerenspw
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8080
debug: true