server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/beerens/beerens
    username: beerens
    password: beerenspw
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
