spring:
  datasource:
    url: jdbc:mysql://localhost/beerensfactuur
    username: beerensfactuur
    password: beerensfactuurpw
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8081