spring:
  datasource:
    url: jdbc:mysql://localhost/beerensautosoort
    username: beerensautosoort
    password: beerensautosoortpw
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8082